# Generated by Django 5.2.17 on 2026-10-06 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InspectionPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="aangemaakt op"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="gewijzigd op"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="keurpunt"
                    ),
                ),
                (
                    "point_type",
                    models.CharField(
                        choices=[
                            ("gcp", "Grenscontrolepost (GCP/BCP)"),
                            ("cp", "Controlepunt"),
                            ("warehouse", "Koel-/vrieshuis met keurfaciliteit"),
                            ("other", "Overig"),
                        ],
                        default="gcp",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "traces_code",
                    models.CharField(
                        blank=True,
                        help_text="Bijv. NLRTM4.",
                        max_length=40,
                        verbose_name="TRACES / BCP-code",
                    ),
                ),
                (
                    "street",
                    models.CharField(blank=True, max_length=200, verbose_name="adres"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="plaats"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="telefoon"
                    ),
                ),
                (
                    "opening_hours",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="openingstijden"
                    ),
                ),
                (
                    "handles_veterinary",
                    models.BooleanField(
                        default=True, verbose_name="veterinair (LNV/NVWA)"
                    ),
                ),
                (
                    "handles_phytosanitary",
                    models.BooleanField(default=False, verbose_name="fytosanitair"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="opmerkingen")),
                ("active", models.BooleanField(default=True, verbose_name="actief")),
            ],
            options={
                "verbose_name": "keurpunt",
                "verbose_name_plural": "keurpunten",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RoadCarrier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="aangemaakt op"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="gewijzigd op"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="vervoerder"
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="contactpersoon"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="telefoon"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="plaats"),
                ),
                (
                    "country",
                    models.CharField(blank=True, max_length=100, verbose_name="land"),
                ),
                (
                    "reefer_capable",
                    models.BooleanField(
                        default=True, verbose_name="koel/vries transport"
                    ),
                ),
                ("adr_capable", models.BooleanField(default=False, verbose_name="ADR")),
                ("notes", models.TextField(blank=True, verbose_name="opmerkingen")),
                ("active", models.BooleanField(default=True, verbose_name="actief")),
            ],
            options={
                "verbose_name": "vervoerder",
                "verbose_name_plural": "vervoerders",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ShippingLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="aangemaakt op"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="gewijzigd op"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="rederij"
                    ),
                ),
                (
                    "scac",
                    models.CharField(
                        blank=True,
                        help_text="Bijv. MAEU, MSCU, CMDU, HLCU.",
                        max_length=4,
                        verbose_name="SCAC-code",
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="website")),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="contact e-mail"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="contact telefoon"
                    ),
                ),
                (
                    "tracking_provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Standaard (instelling TRACKING_DEFAULT_PROVIDER)"),
                            ("mock", "Demo / test (geen echte API)"),
                            ("dcsa", "DCSA Track & Trace (REST)"),
                            ("none", "Geen automatische tracking"),
                        ],
                        max_length=20,
                        verbose_name="tracking provider",
                    ),
                ),
                (
                    "api_base_url",
                    models.URLField(
                        blank=True,
                        help_text="Bijv. https://api.rederij.com/track-and-trace/v2 (DCSA).",
                        verbose_name="API base URL",
                    ),
                ),
                (
                    "api_key_env",
                    models.CharField(
                        blank=True,
                        help_text="Naam van de environment variable waarin de API-sleutel staat (de sleutel zelf wordt niet in de database bewaard).",
                        max_length=100,
                        verbose_name="omgevingsvariabele met API-sleutel",
                    ),
                ),
                (
                    "api_key_header",
                    models.CharField(
                        blank=True,
                        default="Consumer-Key",
                        max_length=60,
                        verbose_name="header voor API-sleutel",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="opmerkingen")),
                ("active", models.BooleanField(default=True, verbose_name="actief")),
            ],
            options={
                "verbose_name": "rederij",
                "verbose_name_plural": "rederijen",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="aangemaakt op"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="gewijzigd op"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="klantnaam"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Interne debiteur- of klantcode.",
                        max_length=30,
                        verbose_name="klantcode",
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="nationaliteit / land"
                    ),
                ),
                (
                    "vat_number",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="btw-nummer"
                    ),
                ),
                (
                    "eori_number",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="EORI-nummer"
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="straat + huisnummer"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="postcode"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="plaats"),
                ),
                (
                    "country",
                    models.CharField(blank=True, max_length=100, verbose_name="land"),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="contactpersoon"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="telefoon"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, verbose_name="opmerkingen / werkinstructies"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="actief")),
                (
                    "account_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_customers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="accountmanager",
                    ),
                ),
            ],
            options={
                "verbose_name": "klant",
                "verbose_name_plural": "klanten",
                "ordering": ["name"],
            },
        ),
    ]
