# Generated by Django 5.2.17 on 2026-10-06 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="tijdstip"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Aangemaakt"),
                            ("update", "Gewijzigd"),
                            ("delete", "Verwijderd"),
                            ("event", "Gebeurtenis"),
                        ],
                        max_length=10,
                        verbose_name="actie",
                    ),
                ),
                (
                    "object_id",
                    models.CharField(blank=True, db_index=True, max_length=40),
                ),
                (
                    "object_repr",
                    models.CharField(max_length=250, verbose_name="object"),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="wijzigingen"
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="toelichting"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="gebruiker",
                    ),
                ),
            ],
            options={
                "verbose_name": "logregel",
                "verbose_name_plural": "wijzigingslog",
                "ordering": ["-timestamp", "-id"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="core_auditl_content_fec0c4_idx",
                    )
                ],
            },
        ),
    ]
