# Generated by Django 5.2.17 on 2026-10-06 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auditlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("last_run", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shipment_scope",
                    models.CharField(
                        choices=[
                            ("mine", "Alleen dossiers waar ik behandelaar ben"),
                            ("all", "Alle dossiers"),
                        ],
                        default="mine",
                        max_length=10,
                        verbose_name="zendingmeldingen voor",
                    ),
                ),
                (
                    "vessel_change",
                    models.BooleanField(
                        default=True, verbose_name="container van schip gewisseld"
                    ),
                ),
                (
                    "eta_change",
                    models.BooleanField(default=True, verbose_name="ETA verschoven"),
                ),
                (
                    "eta_threshold_hours",
                    models.PositiveSmallIntegerField(
                        default=12, verbose_name="ETA-melding vanaf (uur verschuiving)"
                    ),
                ),
                (
                    "action_assigned",
                    models.BooleanField(
                        default=True, verbose_name="actie aan mij toegewezen"
                    ),
                ),
                (
                    "escalations",
                    models.BooleanField(
                        default=False, verbose_name="nieuwe escalaties / niveau omhoog"
                    ),
                ),
                (
                    "daily_digest",
                    models.BooleanField(
                        default=True, verbose_name="dagelijks overzicht ('s ochtends)"
                    ),
                ),
                (
                    "shift_reminder",
                    models.BooleanField(
                        default=True, verbose_name="herinnering dag vóór mijn dienst"
                    ),
                ),
                (
                    "swap_requests",
                    models.BooleanField(
                        default=True, verbose_name="ruilverzoeken diensten"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_prefs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "meldingsvoorkeur",
                "verbose_name_plural": "meldingsvoorkeuren",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_users",
                        to="core.customer",
                        verbose_name="klant (klantportaal)",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "accountprofiel",
                "verbose_name_plural": "accountprofielen",
            },
        ),
    ]
