# Generated by Django 5.2.17 on 2026-10-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_jobrun_notificationpreference_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingline",
            name="oauth_client_id_env",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="omgevingsvariabele met client-ID",
            ),
        ),
        migrations.AddField(
            model_name="shippingline",
            name="oauth_client_secret_env",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="omgevingsvariabele met client-secret",
            ),
        ),
        migrations.AddField(
            model_name="shippingline",
            name="oauth_token_url",
            field=models.URLField(
                blank=True,
                help_text="Alleen nodig als de rederij OAuth2 (client credentials) gebruikt, bijv. Maersk of de private API van CMA CGM.",
                verbose_name="OAuth2 token-URL",
            ),
        ),
    ]
