# Generated by Django 5.2.17 on 2026-10-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_terminal49"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingline",
            name="tracking_provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Standaard (instelling TRACKING_DEFAULT_PROVIDER)"),
                    ("mock", "Demo / test (geen echte API)"),
                    ("dcsa", "DCSA Track & Trace (REST)"),
                    ("terminal49", "Terminal49 (alle rederijen via één API)"),
                    ("safecube", "Safecube / Sinay (alle rederijen via één API)"),
                    ("none", "Geen automatische tracking"),
                ],
                max_length=20,
                verbose_name="tracking provider",
            ),
        ),
    ]
