# Generated by Django 5.2.17 on 2026-10-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_safecube"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingline",
            name="tracking_url_template",
            field=models.CharField(
                blank=True,
                help_text="Bijv. https://www.rederij.com/track?ref={number}. {container} = containernummer, {number} = B/L of boeking.",
                max_length=300,
                verbose_name="link naar trackingpagina",
            ),
        ),
    ]
