# Generated by Django 5.2.18 on 2026-10-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_tracking_urls"),
    ]

    operations = [
        migrations.CreateModel(
            name="Port",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="aangemaakt op"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="gewijzigd op"),
                ),
                (
                    "locode",
                    models.CharField(
                        help_text="Bijv. NLRTM (landcode + 3 tekens).",
                        max_length=5,
                        unique=True,
                        verbose_name="UN/LOCODE",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="naam")),
                (
                    "aliases",
                    models.CharField(
                        blank=True,
                        help_text="Komma-gescheiden namen zoals ze op B/L's of trackingpagina's staan, bijv. ANTWERP, ANVERS.",
                        max_length=300,
                        verbose_name="andere schrijfwijzen",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="actief")),
            ],
            options={
                "verbose_name": "haven",
                "verbose_name_plural": "havens",
                "ordering": ["locode"],
            },
        ),
    ]
