# Generated by Django 5.2.18 on 2026-10-06 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_seed_ports"),
    ]

    operations = [
        migrations.CreateModel(
            name="Terminal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="aangemaakt op"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="gewijzigd op"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="volledige naam"
                    ),
                ),
                (
                    "aliases",
                    models.CharField(
                        blank=True,
                        help_text="Komma-gescheiden, zoals rederijen en trackingdiensten de terminal noemen, bijv. ECT EUROMAX ROTTERDAM, EUROMAX.",
                        max_length=400,
                        verbose_name="andere schrijfwijzen",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="actief")),
                (
                    "port",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="terminals",
                        to="core.port",
                        verbose_name="haven",
                    ),
                ),
            ],
            options={
                "verbose_name": "terminal",
                "verbose_name_plural": "terminals",
                "ordering": ["name"],
            },
        ),
    ]
