# Generated by Django 5.2.18 on 2026-10-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_seed_terminals"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="terminal",
            options={
                "ordering": ["port__locode", "name"],
                "verbose_name": "terminal",
                "verbose_name_plural": "terminals",
            },
        ),
        migrations.AddField(
            model_name="port",
            name="container_port",
            field=models.BooleanField(
                default=False,
                help_text="Komt in de suggesties en gaat voor bij havens met dezelfde naam (bijv. Manzanillo).",
                verbose_name="containerhaven",
            ),
        ),
        migrations.AddField(
            model_name="terminal",
            name="address",
            field=models.CharField(blank=True, max_length=250, verbose_name="adres"),
        ),
        migrations.AddField(
            model_name="terminal",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Bijv. EMX voor ECT Euromax.",
                max_length=10,
                verbose_name="terminalcode (SMDG)",
            ),
        ),
        migrations.AddField(
            model_name="terminal",
            name="company",
            field=models.CharField(blank=True, max_length=150, verbose_name="bedrijf"),
        ),
        migrations.AddField(
            model_name="terminal",
            name="website",
            field=models.URLField(blank=True, max_length=250, verbose_name="website"),
        ),
        migrations.AlterField(
            model_name="terminal",
            name="name",
            field=models.CharField(max_length=150, verbose_name="volledige naam"),
        ),
        migrations.AddConstraint(
            model_name="terminal",
            constraint=models.UniqueConstraint(
                condition=models.Q(("code", ""), _negated=True),
                fields=("port", "code"),
                name="unique_terminal_code_per_port",
            ),
        ),
    ]
