# Generated by Django 5.2.18 on 2026-10-07 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_import_ports_terminals"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="aangemaakt op"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="gewijzigd op"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Korte naam om te kiezen, bijv. 'Ter Maten Bunschoten'.",
                        max_length=100,
                        verbose_name="naam",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("los", "Losadres"),
                            ("laad", "Laadadres"),
                            ("beide", "Laad- en losadres"),
                        ],
                        default="los",
                        max_length=10,
                        verbose_name="soort",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="standaard losadres van deze klant"
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="bedrijfsnaam"
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="straat + huisnummer"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="postcode"
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="plaats")),
                (
                    "country",
                    models.CharField(
                        default="Nederland", max_length=100, verbose_name="land"
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="contactpersoon"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="telefoon"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail"
                    ),
                ),
                (
                    "opening_hours",
                    models.CharField(
                        blank=True,
                        help_text="Bijv. ma-vr 06:00-15:00.",
                        max_length=200,
                        verbose_name="ontvangsttijden",
                    ),
                ),
                (
                    "booking_required",
                    models.BooleanField(
                        default=False,
                        verbose_name="tijdslot / vooraanmelding verplicht",
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text="Bijv. melden bij portier, dock 4, max. 13,6 m, pallets ruilen.",
                        verbose_name="instructies voor de chauffeur",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="actief")),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leeg laten voor een adres dat voor meerdere klanten gebruikt wordt (bijv. een koelhuis).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="core.customer",
                        verbose_name="klant",
                    ),
                ),
            ],
            options={
                "verbose_name": "adres",
                "verbose_name_plural": "adressen",
                "ordering": ["name"],
            },
        ),
    ]
