# Generated by Django 5.2.18 on 2026-10-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_list_preference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="kind",
            field=models.CharField(
                choices=[
                    ("los", "Losadres"),
                    ("laad", "Laadadres"),
                    ("beide", "Laad- en losadres"),
                    ("tussen", "Tussenstop (opslag, koelhuis, lab)"),
                ],
                default="los",
                max_length=10,
                verbose_name="soort",
            ),
        ),
    ]
