# Generated by Django 5.2.17 on 2026-10-06 08:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("meetings", "0001_initial"),
        ("planning", "0001_initial"),
        ("shipments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="aangemaakt op"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="gewijzigd op"),
                ),
                ("title", models.CharField(max_length=250, verbose_name="titel")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="omschrijving"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("actie", "Actie"), ("escalatie", "Escalatie")],
                        default="actie",
                        max_length=20,
                        verbose_name="soort",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("bezig", "In behandeling"),
                            ("wacht", "Wacht op derden"),
                            ("gereed", "Gereed"),
                            ("vervallen", "Vervallen"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Laag"),
                            (2, "Normaal"),
                            (3, "Hoog"),
                            (4, "Urgent"),
                        ],
                        default=2,
                        verbose_name="prioriteit",
                    ),
                ),
                (
                    "escalation_level",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "1 - Teamleider / supervisor"),
                            (2, "2 - OPS management"),
                            (3, "3 - Directie"),
                            (4, "4 - Extern (klant / rederij / vervoerder)"),
                        ],
                        null=True,
                        verbose_name="escalatieniveau",
                    ),
                ),
                (
                    "escalated_to",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="geëscaleerd naar"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="deadline"),
                ),
                (
                    "resolution",
                    models.TextField(
                        blank=True, verbose_name="oplossing / afhandeling"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="afgerond op"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions",
                        to="core.customer",
                        verbose_name="klant",
                    ),
                ),
                (
                    "meeting_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions",
                        to="meetings.meetingitem",
                        verbose_name="uit overlegpunt",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions",
                        to="planning.employee",
                        verbose_name="eigenaar",
                    ),
                ),
                (
                    "road_transport",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions",
                        to="shipments.roadtransport",
                        verbose_name="wegtransport",
                    ),
                ),
                (
                    "sea_shipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions",
                        to="shipments.seashipment",
                        verbose_name="zeevracht dossier",
                    ),
                ),
            ],
            options={
                "verbose_name": "actie / escalatie",
                "verbose_name_plural": "acties & escalaties",
                "ordering": ["-priority", "due_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExtraCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="aangemaakt op"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="gewijzigd op"),
                ),
                (
                    "cost_type",
                    models.CharField(
                        choices=[
                            ("demurrage", "Demurrage"),
                            ("detention", "Detention"),
                            ("opslag", "Opslag / plugin"),
                            ("keuring", "Keurkosten / extra inspectie"),
                            ("wachttijd", "Wachttijd vervoerder"),
                            ("transport", "Extra transport / herlevering"),
                            ("douane", "Douane"),
                            ("overig", "Overig"),
                        ],
                        default="overig",
                        max_length=20,
                        verbose_name="soort kosten",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=250, verbose_name="omschrijving"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="bedrag"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EUR", max_length=3, verbose_name="valuta"
                    ),
                ),
                (
                    "responsibility",
                    models.CharField(
                        choices=[
                            ("klant", "Klant"),
                            ("cory", "Wij (Cory Brothers)"),
                            ("vervoerder", "Vervoerder / rederij"),
                            ("overmacht", "Overmacht"),
                        ],
                        max_length=20,
                        verbose_name="verantwoordelijk",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Nog beoordelen"),
                            ("doorbelasten", "Door te belasten"),
                            ("doorbelast", "Doorbelast / gefactureerd"),
                            ("geclaimd", "Geclaimd bij vervoerder"),
                            ("afgeboekt", "Afgeboekt (eigen kosten)"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "cost_date",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="datum"
                    ),
                ),
                (
                    "invoice_reference",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="factuur- / claimreferentie",
                    ),
                ),
                (
                    "action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="costs",
                        to="actions.action",
                        verbose_name="actie / escalatie",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="extra_costs",
                        to="core.customer",
                        verbose_name="klant",
                    ),
                ),
                (
                    "road_transport",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="extra_costs",
                        to="shipments.roadtransport",
                        verbose_name="wegtransport",
                    ),
                ),
                (
                    "sea_shipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="extra_costs",
                        to="shipments.seashipment",
                        verbose_name="zeevracht dossier",
                    ),
                ),
            ],
            options={
                "verbose_name": "extra kosten",
                "verbose_name_plural": "extra kosten",
                "ordering": ["-cost_date", "-created_at"],
            },
        ),
    ]
