# Generated by Django 5.2.17 on 2026-10-06 08:27

import django.db.models.deletion
import django.utils.timezone
import shipments.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("planning", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SeaShipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="aangemaakt op"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="gewijzigd op"),
                ),
                (
                    "customer_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="klantreferentie"
                    ),
                ),
                (
                    "cory_reference",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="Cory referentie",
                    ),
                ),
                (
                    "container_number",
                    models.CharField(
                        db_index=True,
                        max_length=11,
                        validators=[shipments.validators.validate_container_number],
                        verbose_name="containernummer",
                    ),
                ),
                (
                    "container_type",
                    models.CharField(
                        choices=[
                            ("20DV", "20' Dry"),
                            ("40DV", "40' Dry"),
                            ("40HC", "40' High Cube"),
                            ("20RF", "20' Reefer"),
                            ("40RH", "40' Reefer High Cube"),
                            ("other", "Overig"),
                        ],
                        default="40RH",
                        max_length=10,
                        verbose_name="containertype",
                    ),
                ),
                (
                    "seal_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="zegelnummer"
                    ),
                ),
                (
                    "bl_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=60,
                        verbose_name="B/L-nummer",
                    ),
                ),
                (
                    "booking_number",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="boekingsnummer"
                    ),
                ),
                (
                    "vessel_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="zeeschip (vessel)"
                    ),
                ),
                (
                    "vessel_imo",
                    models.CharField(blank=True, max_length=10, verbose_name="IMO"),
                ),
                (
                    "voyage",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="reisnummer"
                    ),
                ),
                (
                    "original_vessel_name",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="oorspronkelijk zeeschip",
                    ),
                ),
                (
                    "vessel_changed",
                    models.BooleanField(
                        default=False, verbose_name="van schip gewisseld"
                    ),
                ),
                (
                    "vessel_changed_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="schipwissel gedetecteerd op",
                    ),
                ),
                (
                    "port_of_loading",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="laadhaven (POL)"
                    ),
                ),
                (
                    "port_of_discharge",
                    models.CharField(
                        default="NLRTM",
                        help_text="UN/LOCODE, bijv. NLRTM.",
                        max_length=100,
                        verbose_name="loshaven (POD)",
                    ),
                ),
                (
                    "terminal",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="terminal"
                    ),
                ),
                (
                    "eta",
                    models.DateTimeField(blank=True, null=True, verbose_name="ETA"),
                ),
                (
                    "eta_original",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="oorspronkelijke ETA"
                    ),
                ),
                (
                    "ata",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ATA (werkelijke aankomst)"
                    ),
                ),
                (
                    "discharged_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="gelost op"
                    ),
                ),
                (
                    "free_time_until",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="vrije dagen t/m (demurrage)",
                    ),
                ),
                (
                    "inspection_required",
                    models.BooleanField(default=True, verbose_name="keuringsplichtig"),
                ),
                (
                    "ched_number",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="CHED-nummer (TRACES)"
                    ),
                ),
                (
                    "inspection_status",
                    models.CharField(
                        choices=[
                            ("n.v.t.", "Niet keuringsplichtig"),
                            ("aan_te_melden", "Nog aanmelden (CHED)"),
                            ("aangemeld", "Aangemeld bij keurpunt"),
                            ("documentair", "Documentcontrole"),
                            ("gepland", "Fysieke keuring gepland"),
                            ("in_keuring", "In keuring"),
                            ("vrijgegeven", "Vrijgegeven"),
                            ("afgekeurd", "Afgekeurd / geweigerd"),
                        ],
                        default="aan_te_melden",
                        max_length=20,
                        verbose_name="keuringsstatus",
                    ),
                ),
                (
                    "inspection_planned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="keuring gepland op"
                    ),
                ),
                (
                    "customs_cleared",
                    models.BooleanField(default=False, verbose_name="douane vrij"),
                ),
                (
                    "goods_description",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="goederenomschrijving"
                    ),
                ),
                (
                    "temperature_setpoint",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="temperatuur setpoint (°C)",
                    ),
                ),
                (
                    "gross_weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=10,
                        null=True,
                        verbose_name="brutogewicht (kg)",
                    ),
                ),
                (
                    "packages",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="colli"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("verwacht", "Verwacht / onderweg"),
                            ("aangekomen", "Aangekomen (gelost)"),
                            ("keuring", "In keuring / douane"),
                            ("vrij", "Vrijgegeven"),
                            ("uitgeleverd", "Uitgeleverd"),
                            ("afgerond", "Afgerond"),
                            ("geannuleerd", "Geannuleerd"),
                        ],
                        default="verwacht",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="opmerkingen")),
                (
                    "tracking_enabled",
                    models.BooleanField(
                        default=True, verbose_name="automatische tracking"
                    ),
                ),
                (
                    "tracking_last_checked",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="laatst gecontroleerd"
                    ),
                ),
                (
                    "tracking_last_error",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="laatste trackingfout"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sea_shipments",
                        to="core.customer",
                        verbose_name="klant",
                    ),
                ),
                (
                    "handler",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sea_shipments",
                        to="planning.employee",
                        verbose_name="behandelaar",
                    ),
                ),
                (
                    "inspection_point",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sea_shipments",
                        to="core.inspectionpoint",
                        verbose_name="keurpunt",
                    ),
                ),
                (
                    "shipping_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipments",
                        to="core.shippingline",
                        verbose_name="rederij",
                    ),
                ),
            ],
            options={
                "verbose_name": "zeevracht dossier",
                "verbose_name_plural": "zeevracht dossiers",
                "ordering": ["eta", "container_number"],
                "permissions": [
                    ("refresh_tracking", "Mag tracking handmatig verversen")
                ],
            },
        ),
        migrations.CreateModel(
            name="RoadTransport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="aangemaakt op"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="gewijzigd op"),
                ),
                (
                    "customer_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="klantreferentie"
                    ),
                ),
                (
                    "cory_reference",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        verbose_name="Cory referentie",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("import", "Import (vanaf haven/keurpunt)"),
                            ("export", "Export"),
                            ("nationaal", "Nationaal / overig"),
                        ],
                        default="import",
                        max_length=20,
                        verbose_name="richting",
                    ),
                ),
                (
                    "truck_plate",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="kenteken trekker"
                    ),
                ),
                (
                    "trailer_plate",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="kenteken trailer"
                    ),
                ),
                (
                    "driver_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="chauffeur"
                    ),
                ),
                (
                    "driver_phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="telefoon chauffeur"
                    ),
                ),
                (
                    "cmr_number",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="CMR-nummer"
                    ),
                ),
                (
                    "loading_place",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="laadadres"
                    ),
                ),
                (
                    "loading_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="laden gepland"
                    ),
                ),
                (
                    "unloading_place",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="losadres"
                    ),
                ),
                (
                    "delivery_planned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="levering gepland"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="geleverd op"
                    ),
                ),
                (
                    "inspection_required",
                    models.BooleanField(default=True, verbose_name="keuringsplichtig"),
                ),
                (
                    "ched_number",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="CHED-nummer (TRACES)"
                    ),
                ),
                (
                    "inspection_status",
                    models.CharField(
                        choices=[
                            ("n.v.t.", "Niet keuringsplichtig"),
                            ("aan_te_melden", "Nog aanmelden (CHED)"),
                            ("aangemeld", "Aangemeld bij keurpunt"),
                            ("documentair", "Documentcontrole"),
                            ("gepland", "Fysieke keuring gepland"),
                            ("in_keuring", "In keuring"),
                            ("vrijgegeven", "Vrijgegeven"),
                            ("afgekeurd", "Afgekeurd / geweigerd"),
                        ],
                        default="aan_te_melden",
                        max_length=20,
                        verbose_name="keuringsstatus",
                    ),
                ),
                (
                    "inspection_planned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="keuring gepland op"
                    ),
                ),
                (
                    "goods_description",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="goederenomschrijving"
                    ),
                ),
                (
                    "temperature_setpoint",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="temperatuur (°C)",
                    ),
                ),
                (
                    "pallets",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="pallets"
                    ),
                ),
                (
                    "gross_weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=10,
                        null=True,
                        verbose_name="brutogewicht (kg)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("gepland", "Gepland"),
                            ("onderweg", "Onderweg"),
                            ("keurpunt", "Bij keurpunt"),
                            ("geleverd", "Geleverd"),
                            ("afgerond", "Afgerond"),
                            ("geannuleerd", "Geannuleerd"),
                        ],
                        default="gepland",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="opmerkingen")),
                (
                    "carrier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transports",
                        to="core.roadcarrier",
                        verbose_name="vervoerder",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="road_transports",
                        to="core.customer",
                        verbose_name="klant",
                    ),
                ),
                (
                    "handler",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="road_transports",
                        to="planning.employee",
                        verbose_name="behandelaar",
                    ),
                ),
                (
                    "inspection_point",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="road_transports",
                        to="core.inspectionpoint",
                        verbose_name="keurpunt",
                    ),
                ),
                (
                    "sea_shipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="road_transports",
                        to="shipments.seashipment",
                        verbose_name="gekoppelde zeecontainer",
                    ),
                ),
            ],
            options={
                "verbose_name": "wegtransport",
                "verbose_name_plural": "wegtransporten",
                "ordering": ["loading_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrackingUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "checked_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="gecontroleerd op",
                    ),
                ),
                ("provider", models.CharField(max_length=30, verbose_name="bron")),
                ("success", models.BooleanField(default=True)),
                (
                    "eta",
                    models.DateTimeField(blank=True, null=True, verbose_name="ETA"),
                ),
                (
                    "ata",
                    models.DateTimeField(blank=True, null=True, verbose_name="ATA"),
                ),
                (
                    "vessel_name",
                    models.CharField(blank=True, max_length=150, verbose_name="schip"),
                ),
                (
                    "vessel_imo",
                    models.CharField(blank=True, max_length=10, verbose_name="IMO"),
                ),
                (
                    "voyage",
                    models.CharField(blank=True, max_length=40, verbose_name="reis"),
                ),
                (
                    "eta_changed",
                    models.BooleanField(default=False, verbose_name="ETA gewijzigd"),
                ),
                (
                    "vessel_changed",
                    models.BooleanField(default=False, verbose_name="schip gewisseld"),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="melding"
                    ),
                ),
                (
                    "raw",
                    models.JSONField(
                        blank=True, null=True, verbose_name="ruwe respons"
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_updates",
                        to="shipments.seashipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "trackingupdate",
                "verbose_name_plural": "trackingupdates",
                "ordering": ["-checked_at"],
            },
        ),
    ]
