# Generated by Django 5.2.17 on 2026-10-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="seashipment",
            name="external_tracking_id",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=60,
                verbose_name="extern tracking-ID",
            ),
        ),
    ]
