# Generated by Django 5.2.17 on 2026-10-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0002_terminal49"),
    ]

    operations = [
        migrations.AddField(
            model_name="seashipment",
            name="departed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="vertrokken uit laadhaven (ATD)"
            ),
        ),
    ]
