# Generated by Django 5.2.18 on 2026-10-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0003_detail_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="seashipment",
            name="package_type",
            field=models.CharField(
                blank=True,
                help_text="Bijv. CARTONS, PALLETS.",
                max_length=40,
                verbose_name="verpakking",
            ),
        ),
        migrations.AlterField(
            model_name="roadtransport",
            name="gross_weight_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=12,
                null=True,
                verbose_name="brutogewicht (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="seashipment",
            name="gross_weight_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=12,
                null=True,
                verbose_name="brutogewicht (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="seashipment",
            name="port_of_discharge",
            field=models.CharField(
                default="NLRTM",
                help_text="UN/LOCODE of havennaam, bijv. NLRTM of Rotterdam.",
                max_length=100,
                verbose_name="loshaven (POD)",
            ),
        ),
        migrations.AlterField(
            model_name="seashipment",
            name="port_of_loading",
            field=models.CharField(
                blank=True,
                help_text="UN/LOCODE of havennaam; bekende havens worden omgezet naar de code.",
                max_length=100,
                verbose_name="laadhaven (POL)",
            ),
        ),
    ]
