# Generated by Django 5.2.18 on 2026-10-07 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_address"),
        ("shipments", "0005_port_codes"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadtransport",
            name="delivery_window_until",
            field=models.DateTimeField(
                blank=True,
                help_text="Einde van het tijdvenster.",
                null=True,
                verbose_name="levering uiterlijk",
            ),
        ),
        migrations.AddField(
            model_name="roadtransport",
            name="driver_instructions",
            field=models.TextField(
                blank=True, verbose_name="instructies voor de chauffeur"
            ),
        ),
        migrations.AddField(
            model_name="roadtransport",
            name="empty_return_by",
            field=models.DateField(
                blank=True, null=True, verbose_name="lege retour uiterlijk"
            ),
        ),
        migrations.AddField(
            model_name="roadtransport",
            name="empty_return_place",
            field=models.CharField(
                blank=True,
                help_text="Depot of terminal.",
                max_length=200,
                verbose_name="lege container retour naar",
            ),
        ),
        migrations.AddField(
            model_name="roadtransport",
            name="loading_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.address",
                verbose_name="laadadres uit adresboek",
            ),
        ),
        migrations.AddField(
            model_name="roadtransport",
            name="loading_reference",
            field=models.CharField(
                blank=True,
                help_text="Pincode / release- of pick-upreferentie.",
                max_length=100,
                verbose_name="referentie ophalen",
            ),
        ),
        migrations.AddField(
            model_name="roadtransport",
            name="transport_type",
            field=models.CharField(
                choices=[
                    ("container", "Containertransport (container op chassis)"),
                    ("koeltrailer", "Koeltrailer / losse lading"),
                    ("overig", "Overig"),
                ],
                default="container",
                max_length=20,
                verbose_name="soort transport",
            ),
        ),
        migrations.AddField(
            model_name="roadtransport",
            name="unloading_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.address",
                verbose_name="losadres uit adresboek",
            ),
        ),
        migrations.AddField(
            model_name="roadtransport",
            name="unloading_reference",
            field=models.CharField(
                blank=True,
                help_text="Ordernummer of tijdslot bij de ontvanger.",
                max_length=100,
                verbose_name="referentie lossen",
            ),
        ),
        migrations.AlterField(
            model_name="roadtransport",
            name="direction",
            field=models.CharField(
                choices=[
                    ("import", "Import: haven/keurpunt → klant"),
                    ("export", "Export: klant → haven"),
                    ("nationaal", "Binnenland / overig"),
                ],
                default="import",
                help_text="Import: de container wordt opgehaald bij de terminal (eventueel via het keurpunt) en bij de klant gelost.",
                max_length=20,
                verbose_name="richting",
            ),
        ),
        migrations.AlterField(
            model_name="roadtransport",
            name="loading_place",
            field=models.CharField(
                blank=True,
                help_text="Bijv. de terminal waar de container staat.",
                max_length=250,
                verbose_name="laadadres",
            ),
        ),
    ]
