# Generated by Django 5.2.18 on 2026-10-07 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_address_kind_stop"),
        ("shipments", "0006_road_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="seashipment",
            name="lab_expected_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="uitslag verwacht"
            ),
        ),
        migrations.AddField(
            model_name="seashipment",
            name="lab_notes",
            field=models.CharField(
                blank=True,
                help_text="Bijv. laboratorium, onderzochte parameters.",
                max_length=250,
                verbose_name="opmerking labonderzoek",
            ),
        ),
        migrations.AddField(
            model_name="seashipment",
            name="lab_result_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="uitslag ontvangen op"
            ),
        ),
        migrations.AddField(
            model_name="seashipment",
            name="lab_sampled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="monster genomen op"
            ),
        ),
        migrations.AddField(
            model_name="seashipment",
            name="lab_status",
            field=models.CharField(
                choices=[
                    ("geen", "Geen labonderzoek"),
                    ("monster", "Monster genomen, wacht op uitslag"),
                    ("goed", "Uitslag goed, vrijgegeven"),
                    ("afgekeurd", "Uitslag afgekeurd"),
                ],
                default="geen",
                max_length=20,
                verbose_name="labonderzoek",
            ),
        ),
        migrations.AlterField(
            model_name="roadtransport",
            name="status",
            field=models.CharField(
                choices=[
                    ("gepland", "Gepland"),
                    ("onderweg", "Onderweg"),
                    ("keurpunt", "Bij keurpunt"),
                    ("tussenstop", "Bij tussenstop / in opslag"),
                    ("geleverd", "Geleverd"),
                    ("afgerond", "Afgerond"),
                    ("geannuleerd", "Geannuleerd"),
                ],
                default="gepland",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.CreateModel(
            name="TransportStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="volgorde"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("keurpunt", "Keurpunt"),
                            ("lab", "Opslag: wachten op labuitslag"),
                            ("opslag", "Opslag / koelhuis"),
                            ("douane", "Douane"),
                            ("overslag", "Overslag / ander voertuig"),
                            ("overig", "Overig"),
                        ],
                        default="keurpunt",
                        max_length=20,
                        verbose_name="soort",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="plaats / terminal"
                    ),
                ),
                (
                    "planned_arrival",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="aankomst gepland"
                    ),
                ),
                (
                    "planned_departure",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leeg = tot vrijgave / labuitslag.",
                        null=True,
                        verbose_name="vertrek gepland",
                    ),
                ),
                (
                    "arrived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="aangekomen"
                    ),
                ),
                (
                    "departed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="vertrokken"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="referentie"
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="opmerking"
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.address",
                        verbose_name="adres uit adresboek",
                    ),
                ),
                (
                    "inspection_point",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.inspectionpoint",
                        verbose_name="keurpunt",
                    ),
                ),
                (
                    "transport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="shipments.roadtransport",
                        verbose_name="wegtransport",
                    ),
                ),
            ],
            options={
                "verbose_name": "tussenstop",
                "verbose_name_plural": "tussenstops",
                "ordering": ["position", "pk"],
            },
        ),
    ]
