# Generated by Django 5.2.18 on 2026-10-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0007_stops_lab"),
    ]

    operations = [
        migrations.AddField(
            model_name="seashipment",
            name="carrier_release",
            field=models.CharField(
                choices=[
                    ("open", "Nog niet vrijgegeven"),
                    ("aangevraagd", "Vrijgave aangevraagd"),
                    ("vrij", "Vrijgegeven"),
                ],
                default="open",
                max_length=20,
                verbose_name="vrijgave rederij",
            ),
        ),
        migrations.AddField(
            model_name="seashipment",
            name="carrier_released_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="vrijgegeven op"
            ),
        ),
        migrations.AddField(
            model_name="seashipment",
            name="invoice_received_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="invoice ontvangen op"
            ),
        ),
        migrations.AddField(
            model_name="seashipment",
            name="invoice_requested_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="invoice opgevraagd op"
            ),
        ),
        migrations.AddField(
            model_name="seashipment",
            name="invoice_status",
            field=models.CharField(
                choices=[
                    ("niet", "Nog niet opgevraagd"),
                    ("opgevraagd", "Opgevraagd"),
                    ("ontvangen", "Ontvangen"),
                ],
                default="niet",
                max_length=20,
                verbose_name="invoice rederij",
            ),
        ),
        migrations.AddField(
            model_name="seashipment",
            name="local_charges",
            field=models.CharField(
                choices=[
                    ("onbekend", "Nog onbekend"),
                    ("te_betalen", "Nog te betalen"),
                    ("betaald", "Betaald"),
                    ("geen", "Geen lokale kosten"),
                ],
                default="onbekend",
                max_length=20,
                verbose_name="lokale kosten",
            ),
        ),
        migrations.AddField(
            model_name="seashipment",
            name="local_charges_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="bedrag lokale kosten (€)",
            ),
        ),
        migrations.AddField(
            model_name="seashipment",
            name="local_charges_paid_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="lokale kosten betaald op"
            ),
        ),
        migrations.AddField(
            model_name="seashipment",
            name="release_reference",
            field=models.CharField(
                blank=True, max_length=60, verbose_name="pincode / releasenummer"
            ),
        ),
    ]
