# Generated by Django 5.2.18 on 2026-10-07 12:00

from django.db import migrations, models


def merge(apps, schema_editor):
    """'Te betalen' heette eerst zo; de aparte invoicestatus gaat op in de lokale kosten (= factuur rederij)."""
    SeaShipment = apps.get_model("shipments", "SeaShipment")
    SeaShipment.objects.filter(local_charges="te_betalen").update(local_charges="ontvangen")
    SeaShipment.objects.filter(local_charges="onbekend", invoice_status="ontvangen").update(local_charges="ontvangen")
    SeaShipment.objects.filter(local_charges="onbekend", invoice_status="opgevraagd").update(local_charges="opgevraagd")


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0008_release_charges_invoice"),
    ]

    operations = [
        migrations.RunPython(merge, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="seashipment",
            name="invoice_status",
        ),
        migrations.AlterField(
            model_name="seashipment",
            name="invoice_received_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="factuur ontvangen op"
            ),
        ),
        migrations.AlterField(
            model_name="seashipment",
            name="invoice_requested_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="factuur opgevraagd op"
            ),
        ),
        migrations.AlterField(
            model_name="seashipment",
            name="local_charges",
            field=models.CharField(
                choices=[
                    ("onbekend", "Factuur nog niet opgevraagd"),
                    ("opgevraagd", "Factuur opgevraagd"),
                    ("ontvangen", "Factuur ontvangen, te betalen"),
                    ("betaald", "Betaald"),
                    ("geen", "Geen lokale kosten"),
                ],
                default="onbekend",
                max_length=20,
                verbose_name="lokale kosten (factuur rederij)",
            ),
        ),
    ]
