# Generated by Django 5.2.18 on 2026-10-07 12:21

from django.db import migrations, models


def copy_customs(apps, schema_editor):
    # 'Douane vrij = ja' wordt 'Ingeklaard'.
    SeaShipment = apps.get_model("shipments", "SeaShipment")
    SeaShipment.objects.filter(customs_cleared=True).update(customs_status="ingeklaard")


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0009_merge_invoice_into_local_charges"),
    ]

    operations = [
        migrations.AddField(
            model_name="seashipment",
            name="customs_status",
            field=models.CharField(
                choices=[
                    ("open", "Nog niet ingeklaard"),
                    ("t1", "T1 (onder douaneverband)"),
                    ("ingeklaard", "Ingeklaard"),
                ],
                default="open",
                max_length=20,
                verbose_name="douane",
            ),
        ),
        migrations.RunPython(copy_customs, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="seashipment",
            name="customs_cleared",
        ),
        migrations.AlterField(
            model_name="roadtransport",
            name="loading_reference",
            field=models.CharField(
                blank=True,
                help_text="Release- of pick-upreferentie (Portbase).",
                max_length=100,
                verbose_name="referentie ophalen",
            ),
        ),
        migrations.AlterField(
            model_name="seashipment",
            name="carrier_release",
            field=models.CharField(
                choices=[
                    ("open", "Nog geen release"),
                    ("aangevraagd", "Release aangevraagd"),
                    ("vrij", "Release / DO ontvangen"),
                ],
                default="open",
                max_length=20,
                verbose_name="release / delivery order",
            ),
        ),
        migrations.AlterField(
            model_name="seashipment",
            name="carrier_released_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="release ontvangen op"
            ),
        ),
        migrations.AlterField(
            model_name="seashipment",
            name="release_reference",
            field=models.CharField(
                blank=True,
                help_text="Bijv. het delivery-ordernummer of de Portbase-referentie.",
                max_length=60,
                verbose_name="referentie release / DO",
            ),
        ),
    ]
