# Generated by Django 5.2.18 on 2026-10-07 12:35

from django.db import migrations, models


def simplify(apps, schema_editor):
    # Factuur kent alleen nog: nog niet ontvangen / opgevraagd / ontvangen.
    SeaShipment = apps.get_model("shipments", "SeaShipment")
    for shipment in SeaShipment.objects.filter(local_charges__in=["betaald", "geen"]):
        shipment.local_charges = "ontvangen"
        if not shipment.invoice_received_at:
            shipment.invoice_received_at = shipment.local_charges_paid_at or shipment.updated_at
        shipment.save(update_fields=["local_charges", "invoice_received_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0010_customs_status_release"),
    ]

    operations = [
        migrations.RunPython(simplify, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="seashipment",
            name="local_charges_amount",
        ),
        migrations.RemoveField(
            model_name="seashipment",
            name="local_charges_paid_at",
        ),
        migrations.AlterField(
            model_name="seashipment",
            name="carrier_release",
            field=models.CharField(
                choices=[
                    ("open", "Nog niet ontvangen"),
                    ("aangevraagd", "Opgevraagd"),
                    ("vrij", "Vrijgesteld"),
                ],
                default="open",
                max_length=20,
                verbose_name="release",
            ),
        ),
        migrations.AlterField(
            model_name="seashipment",
            name="local_charges",
            field=models.CharField(
                choices=[
                    ("onbekend", "Nog niet ontvangen"),
                    ("opgevraagd", "Opgevraagd"),
                    ("ontvangen", "Ontvangen"),
                ],
                default="onbekend",
                max_length=20,
                verbose_name="factuur",
            ),
        ),
    ]
