# Generated by Django 5.2.17 on 2026-10-06 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("planning", "0001_initial"),
        ("shipments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="aangemaakt op"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="gewijzigd op"),
                ),
                ("date", models.DateField(verbose_name="datum")),
                (
                    "block",
                    models.CharField(
                        choices=[
                            ("ochtend", "Ochtendoverleg"),
                            ("middag", "Middagoverleg"),
                            ("einde_dag", "Einde-dag overleg"),
                        ],
                        max_length=20,
                        verbose_name="overleg",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="algemene notities"),
                ),
                (
                    "attendees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="meeting_blocks",
                        to="planning.employee",
                        verbose_name="aanwezig",
                    ),
                ),
            ],
            options={
                "verbose_name": "overlegmoment",
                "verbose_name_plural": "overlegmomenten",
                "ordering": ["-date", "block"],
                "unique_together": {("date", "block")},
            },
        ),
        migrations.CreateModel(
            name="MeetingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="aangemaakt op"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="gewijzigd op"),
                ),
                (
                    "title",
                    models.CharField(max_length=250, verbose_name="vraag / onderwerp"),
                ),
                ("details", models.TextField(blank=True, verbose_name="toelichting")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("beantwoord", "Beantwoord / afgehandeld"),
                            ("doorgeschoven", "Doorgeschoven"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "answer",
                    models.TextField(blank=True, verbose_name="antwoord / besluit"),
                ),
                (
                    "carried_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="carried_to",
                        to="meetings.meetingitem",
                        verbose_name="doorgeschoven vanuit",
                    ),
                ),
                (
                    "colleagues",
                    models.ManyToManyField(
                        blank=True,
                        related_name="meeting_items",
                        to="planning.employee",
                        verbose_name="gekoppelde collega's",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meeting_items",
                        to="core.customer",
                        verbose_name="klant",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="meetings.meetingblock",
                        verbose_name="overleg",
                    ),
                ),
                (
                    "raised_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="raised_meeting_items",
                        to="planning.employee",
                        verbose_name="ingebracht door",
                    ),
                ),
                (
                    "road_transport",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meeting_items",
                        to="shipments.roadtransport",
                        verbose_name="wegtransport",
                    ),
                ),
                (
                    "sea_shipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meeting_items",
                        to="shipments.seashipment",
                        verbose_name="zeevracht dossier",
                    ),
                ),
            ],
            options={
                "verbose_name": "overlegpunt",
                "verbose_name_plural": "overlegpunten",
                "ordering": ["meeting__date", "created_at"],
            },
        ),
    ]
