# Generated by Django 5.2.17 on 2026-10-06 08:27

import core.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="afdeling / groep"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="omschrijving"
                    ),
                ),
            ],
            options={
                "verbose_name": "afdeling",
                "verbose_name_plural": "afdelingen",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="datum")),
                ("name", models.CharField(max_length=100, verbose_name="feestdag")),
            ],
            options={
                "verbose_name": "feestdag",
                "verbose_name_plural": "feestdagen",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="aangemaakt op"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="gewijzigd op"),
                ),
                (
                    "name",
                    models.CharField(max_length=150, unique=True, verbose_name="naam"),
                ),
                (
                    "job_title",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="functie"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="telefoon"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="actief")),
                (
                    "wfh_days_per_week",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="0 = neemt niet deel aan het thuiswerkschema.",
                        verbose_name="thuiswerkdagen per week",
                    ),
                ),
                (
                    "preferred_wfh_weekdays",
                    core.fields.WeekdaysField(
                        blank=True,
                        default="",
                        help_text="Optioneel; de generator probeert deze dagen te gebruiken.",
                        max_length=20,
                        verbose_name="voorkeur thuiswerkdag(en)",
                    ),
                ),
                (
                    "days_off",
                    core.fields.WeekdaysField(
                        blank=True,
                        default="",
                        help_text="Bijv. woensdag bij een 4-daagse werkweek.",
                        max_length=20,
                        verbose_name="vaste vrije dag(en)",
                    ),
                ),
                (
                    "in_shift_pool",
                    models.BooleanField(
                        default=True, verbose_name="draait avond-/zaterdagdiensten"
                    ),
                ),
                (
                    "no_shift_weekdays",
                    core.fields.WeekdaysField(
                        blank=True,
                        default="",
                        help_text="Weekdagen waarop deze persoon nooit dienst krijgt (bijv. schooldag).",
                        max_length=20,
                        verbose_name="geen dienst op",
                    ),
                ),
                (
                    "calendar_token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="agenda-token",
                    ),
                ),
                (
                    "departments",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Collega's uit dezelfde groep werken nooit op dezelfde of direct opvolgende dag thuis.",
                        related_name="employees",
                        to="planning.department",
                        verbose_name="afdelingsgroepen",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="gekoppeld account",
                    ),
                ),
            ],
            options={
                "verbose_name": "medewerker",
                "verbose_name_plural": "medewerkers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Absence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="aangemaakt op"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="gewijzigd op"),
                ),
                ("start_date", models.DateField(verbose_name="van")),
                ("end_date", models.DateField(verbose_name="t/m")),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("vakantie", "Vakantie / verlof"),
                            ("ziek", "Ziek"),
                            ("school", "School / opleiding"),
                            ("overig", "Overig"),
                        ],
                        default="vakantie",
                        max_length=20,
                        verbose_name="reden",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="toelichting"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absences",
                        to="planning.employee",
                        verbose_name="medewerker",
                    ),
                ),
            ],
            options={
                "verbose_name": "afwezigheid",
                "verbose_name_plural": "afwezigheden",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="RosterMonth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="aangemaakt op"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="gewijzigd op"),
                ),
                ("year", models.PositiveSmallIntegerField(verbose_name="jaar")),
                ("month", models.PositiveSmallIntegerField(verbose_name="maand")),
                (
                    "status",
                    models.CharField(
                        choices=[("concept", "Concept"), ("definitief", "Definitief")],
                        default="concept",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="gegenereerd op"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, verbose_name="opmerkingen / meldingen generator"
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "roostermaand",
                "verbose_name_plural": "roostermaanden",
                "ordering": ["-year", "-month"],
                "permissions": [
                    ("generate_roster", "Mag rooster genereren en vaststellen")
                ],
                "unique_together": {("year", "month")},
            },
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="datum")),
                (
                    "shift_type",
                    models.CharField(
                        choices=[
                            ("avond", "Avonddienst"),
                            ("zaterdag", "Zaterdagdienst"),
                        ],
                        max_length=20,
                        verbose_name="type dienst",
                    ),
                ),
                (
                    "linked_to_wfh",
                    models.BooleanField(
                        default=False, verbose_name="gekoppeld aan thuiswerk"
                    ),
                ),
                (
                    "is_manual",
                    models.BooleanField(
                        default=False,
                        help_text="Handmatige wijzigingen blijven staan bij hergenereren.",
                        verbose_name="handmatig",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="opmerking"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shifts",
                        to="planning.employee",
                        verbose_name="medewerker",
                    ),
                ),
            ],
            options={
                "verbose_name": "dienst",
                "verbose_name_plural": "diensten",
                "ordering": ["date"],
                "unique_together": {("date", "shift_type")},
            },
        ),
        migrations.CreateModel(
            name="WorkFromHomeDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="datum")),
                (
                    "is_manual",
                    models.BooleanField(
                        default=False,
                        help_text="Handmatige wijzigingen blijven staan bij hergenereren.",
                        verbose_name="handmatig",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wfh_days",
                        to="planning.employee",
                        verbose_name="medewerker",
                    ),
                ),
            ],
            options={
                "verbose_name": "thuiswerkdag",
                "verbose_name_plural": "thuiswerkdagen",
                "ordering": ["date", "employee__name"],
                "unique_together": {("employee", "date")},
            },
        ),
    ]
