# Generated by Django 5.2.17 on 2026-10-06 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftSwapRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="aangemaakt op"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="gewijzigd op"),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="bericht"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("wacht_collega", "Wacht op collega"),
                            ("wacht_planner", "Wacht op goedkeuring planner"),
                            ("goedgekeurd", "Goedgekeurd en verwerkt"),
                            ("geweigerd", "Geweigerd door collega"),
                            ("afgewezen", "Afgewezen door planner"),
                            ("ingetrokken", "Ingetrokken"),
                        ],
                        default="wacht_collega",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "decision_note",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="toelichting planner"
                    ),
                ),
                (
                    "colleague",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swap_requests_received",
                        to="planning.employee",
                        verbose_name="collega die overneemt",
                    ),
                ),
                (
                    "colleague_shift",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leeg laten als de collega de dienst overneemt zonder ruil.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="planning.shift",
                        verbose_name="in ruil voor dienst van collega",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swap_requests_sent",
                        to="planning.employee",
                        verbose_name="aanvrager",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swap_requests",
                        to="planning.shift",
                        verbose_name="dienst",
                    ),
                ),
            ],
            options={
                "verbose_name": "ruilverzoek",
                "verbose_name_plural": "ruilverzoeken",
                "ordering": ["-created_at"],
            },
        ),
    ]
