# Generated by Django 5.2.17 on 2026-10-06 08:57

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0002_shiftswaprequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="days_off",
            field=core.fields.WeekdaysField(
                blank=True,
                default=set,
                help_text="Bijv. woensdag bij een 4-daagse werkweek.",
                max_length=20,
                verbose_name="vaste vrije dag(en)",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="no_shift_weekdays",
            field=core.fields.WeekdaysField(
                blank=True,
                default=set,
                help_text="Weekdagen waarop deze persoon nooit dienst krijgt (bijv. schooldag).",
                max_length=20,
                verbose_name="geen dienst op",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="preferred_wfh_weekdays",
            field=core.fields.WeekdaysField(
                blank=True,
                default=set,
                help_text="Optioneel; de generator probeert deze dagen te gebruiken.",
                max_length=20,
                verbose_name="voorkeur thuiswerkdag(en)",
            ),
        ),
    ]
