# Generated by Django 5.2.17 on 2026-10-06 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("shipments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="aangemaakt op"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="gewijzigd op"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="documenten/%Y/%m/", verbose_name="bestand"
                    ),
                ),
                (
                    "original_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="bestandsnaam"
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("bl", "Bill of Lading"),
                            ("arrival_notice", "Arrival notice"),
                            ("invoice", "Handelsfactuur"),
                            ("packing_list", "Paklijst"),
                            ("health_cert", "Gezondheidscertificaat"),
                            ("ched", "CHED"),
                            ("cmr", "CMR"),
                            ("other", "Overig"),
                        ],
                        default="bl",
                        max_length=30,
                        verbose_name="soort document",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("nieuw", "Nieuw"),
                            ("verwerkt", "Tekst herkend"),
                            ("gekoppeld", "Gekoppeld / dossiers aangemaakt"),
                            ("fout", "Herkenning mislukt"),
                        ],
                        default="nieuw",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "extraction_method",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="herkenningsmethode"
                    ),
                ),
                (
                    "extracted_text",
                    models.TextField(blank=True, verbose_name="herkende tekst"),
                ),
                (
                    "extracted_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="herkende gegevens"
                    ),
                ),
                (
                    "error",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="foutmelding"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="core.customer",
                        verbose_name="klant",
                    ),
                ),
                (
                    "road_transports",
                    models.ManyToManyField(
                        blank=True,
                        related_name="documents",
                        to="shipments.roadtransport",
                        verbose_name="wegtransporten",
                    ),
                ),
                (
                    "sea_shipments",
                    models.ManyToManyField(
                        blank=True,
                        related_name="documents",
                        to="shipments.seashipment",
                        verbose_name="zeevracht dossiers",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "document",
                "verbose_name_plural": "documenten",
                "ordering": ["-created_at"],
            },
        ),
    ]
