# Generated by Django 5.2.18 on 2026-10-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="content",
            field=models.BinaryField(blank=True, null=True, verbose_name="inhoud"),
        ),
    ]
